### ISSUE TITLE
review WRTDS 

### ISSUE THREAD

**Issue by westonslaughter** [ecogub/RSFME#36]
@ecogub  WRTDS calcs, when done by site-year, make the occasional extreme outlier. paying close attention to units and conversions, we need to make sure that the source of these outliers is intrinsic to WRTDS and not naything we did

note, make sure to check out `egret_overwrites.R`

**Comment by ecogub** [comment]
Needs unit handling. WRTDS is agnostic on units, but defaults to mg/L.  you can supply a unit using readuserinfo() and param.units. We could use the ms data table to automatically feed this in or use the table to convert everything to mg/L (which i prefer). Since we want to report everything in kg/ha/time I think converting everything to a common unit makes sense.

**Comment by ecogub** [comment]
> Needs unit handling. WRTDS is agnostic on units, but defaults to mg/L. you can supply a unit using readuserinfo() and param.units. We could use the ms data table to automatically feed this in or use the table to convert everything to mg/L (which i prefer). Since we want to report everything in kg/ha/time I think converting everything to a common unit makes sense.

now that I think of it @vlahm probably has some code that does this already somewhere

**Comment by vlahm** [comment]
The macrosheds pipeline uses the `ms_conversions` function [here](https://github.com/MacroSHEDS/data_processing/blob/master/src/global/global_helpers.R), which accepts `from` and `to` units. All our default units can be found [here](https://docs.google.com/spreadsheets/d/1zc1RydnVyAQBdrp-6wBuZl8-gemgIro5893czoGM7mw/edit#gid=0), but note that they're not all mg/L. Also note that this function (and the ones it calls) are pretty ugly. You may have better luck with `NISTunits` or something similar. Chez: [this](https://stackoverflow.com/questions/7214781/converting-units-in-r)

**Comment by westonslaughter** [comment]
Ah! Mike you're back! I should have responded directly to this comment. yes, I have done a wee wrastling with the `ms_conversions`, but in my latest PR to this repo, it is handling the conversion of all stream chem data to g/l from their default units well I believe. that being said, I noticed a few things I would love to add/edit to `ms_conversions` that I would love to chat with you about (I did commit one miniscule edit directly to the package)

as a general comment though, the mass per volume conversions of the main unit handling R packages is surprisingly patchy

**Comment by vlahm** [comment]
Please edit away! Spencer was just getting used to R when most of that was written.

**Comment by westonslaughter** [comment]
closing this issue, PR pending, will open new issues based on the new WRTDS patch. 

a quick summary: on investigating the source of the major outliers in our WRTDS estimations, worst in site-year runs but still present in runs using all available site data, I learned a ton of valuable info, but the factor that was the heart of the issue had to do with the **minNumObs** and **minNumUncen** arguments. we now should have a discussion about how we want to approach this. I'm currently leaning towards making it so that our loop analyzes a given site-solute dataset, and uses the maximum possible minimum obs and uncen for that data 

[here](https://docs.google.com/document/d/1SgnFbtis8-cuknR6otQIZBcljllTX-aapaUeo_zWglM/edit) is a (currently incredibly messy) google doc where Im organizing some thoughts
