### ISSUE TITLE
final WRTDS product caveat 

### ISSUE THREAD

**Issue by westonslaughter** [ecogub/RSFME#42]
@ecogub from our analysis thusfar, it seems like WRTDS should not be run by site-year like other estimates -- we should bring this up in meeting and confirm -- but seems like we need to amend the loop/code so that WRTDS is run by site, and then added to all the other estimates after the site-year loop finishes

**Comment by ecogub** [comment]
agreed. see my comment of WRTDS review issue for my take on it

**Comment by westonslaughter** [comment]
we should revisit site-year WRTDS flux estimates, especially if we decide to use flexible minimums (minNumObs and minUncen) for WRTDS calcs, as well as if we decide to use flexible windows (windowY, windowS, windowQ)
