### ISSUE TITLE
ask at meeting: how should we handle uncertainty estimation

### ISSUE THREAD

**Issue by ecogub** [ecogub/RSFME#50]

**Comment by ecogub** [comment]
also ask: can we run WRTDS with different model params at each site and compare them? (i generally think so)

**Comment by ecogub** [comment]
also ask: providing daily fluxes for methods that produce them, and on a related note, how to express uncertainty around them

**Comment by westonslaughter** [comment]
asked, and now we can open new issues regarding the proposed methods we have discussed, when the time comes to implement
